# Generated by Django 2.2.10 on 2020-02-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
