# Generated by Django 2.2.10 on 2020-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tools_neighbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='available',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='str', max_length=255),
            preserve_default=False,
        ),
    ]
